"""
Generate the reference outputs y_<mode>.txt for test/test_replay.jl, using the
Python UACR replay implementation at a pinned commit (downloaded into tmp/).

Run from the repository root:

    python test/data/gen_references.py

Requires numpy, scipy, h5py and hdf5storage.
"""

import os
import urllib.request
import importlib.util

import numpy as np
import h5py
import hdf5storage

REF_REPO = "uwa-channels/python"
REF_COMMIT = "cdb29f8098566db2d44a0d499a9319800d4c1bbe"
REF_PATH = "src/uwa_channels/replay.py"
REF_URL = f"https://raw.githubusercontent.com/{REF_REPO}/{REF_COMMIT}/{REF_PATH}"

HERE = os.path.dirname(os.path.abspath(__file__))
TMP = os.path.normpath(os.path.join(HERE, "..", "..", "tmp"))

# must match the constants in test_replay.jl
FS_IN, FC, FS_DELAY = 96_000.0, 12_000.0, 24_000.0

# (name, step, snapshots, mode, Doppler in Hz); must match cases in test_replay.jl.
# tv's 80 Hz makes the impulse response vary over the probe, exercising the
# interpolation of h along the time axis
CASES = [
    ("none",  1, 240, None,        3.0),
    ("theta", 1, 240, "theta_hat", 3.0),
    ("phi",   1, 240, "phi_hat",   3.0),
    ("tv",   20, 120, "phi_hat",  80.0),
]


def load_reference():
    os.makedirs(TMP, exist_ok=True)
    path = os.path.join(TMP, "_replay_ref.py")
    if not os.path.exists(path):
        print(f"downloading reference from {REF_URL}")
        urllib.request.urlretrieve(REF_URL, path)
    spec = importlib.util.spec_from_file_location("_replay_ref", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def make_h(L, M, T, step, fd_scale):
    """Must match ref_h in test_replay.jl."""
    i = np.arange(L)[:, None, None]
    j = np.arange(M)[None, :, None]
    k = np.arange(T)[None, None, :]
    g = 0.6**i * np.exp(1j * np.pi * (i + 3 * j) / 7)
    fd = fd_scale * np.sin(1.7 * i + 0.9 * j)
    return g * np.exp(2j * np.pi * fd * k * step / FS_DELAY)


def make_phase(M, nphase):
    """Must match ref_phase in test_replay.jl."""
    q = np.arange(nphase)[None, :]
    m = np.arange(M)[:, None]
    return 0.4 * np.sin(2 * np.pi * 1.3 * q / FS_DELAY + 0.7 * m) + 1.5 * q / FS_DELAY


def make_probe(fs, D=0.008, f0=9_000.0, f1=15_000.0, tau=0.002):
    """Must match ref_probe in test_replay.jl."""
    n = np.arange(int(round(D * fs)))
    t = n / fs
    x = np.cos(2 * np.pi * (f0 * t + 0.5 * (f1 - f0) / D * t * t))
    w = np.ones_like(t)
    w[t < tau] = 0.5 * (1 - np.cos(np.pi * t[t < tau] / tau))
    w[t > D - tau] = 0.5 * (1 - np.cos(np.pi * (D - t[t > D - tau]) / tau))
    return x * w


def py_channel(path):
    """Read the .mat back the way the reference implementation expects."""
    with h5py.File(path, "r") as f:
        hh = f["h_hat"][:]                       # [time, rx, delay]
        ch = {
            "version": f["version"][()],
            "h_hat": {"real": np.array(hh["real"]), "imag": np.array(hh["imag"])},
            "params": {k: f["params"][k][()] for k in f["params"]},
        }
        for key in ("phi_hat", "theta_hat"):
            if key in f:
                ch[key] = f[key][:]              # [time, rx]
    return ch


def main():
    ref = load_reference()
    probe = make_probe(FS_IN)
    L, M = 16, 2

    for name, step, T, mode, fd_scale in CASES:
        fs_time = FS_DELAY / step
        mat = {
            "version": np.array([[1.0]]),
            "h_hat": make_h(L, M, T, step, fd_scale).astype(np.complex128),
            "params": {
                "fs_delay": np.array([[FS_DELAY]]),
                "fs_time": np.array([[fs_time]]),
                "fc": np.array([[FC]]),
            },
        }
        if mode is not None:
            mat[mode] = make_phase(M, T * step)

        tmp = os.path.join(TMP, f"_tmp_{name}.mat")
        if os.path.exists(tmp):
            os.remove(tmp)
        hdf5storage.savemat(tmp, mat, format="7.3", matlab_compatible=True)
        y = np.asarray(ref.replay(probe, FS_IN, np.arange(M), py_channel(tmp), start=0),
                       dtype=np.float64)
        os.remove(tmp)

        out = os.path.join(HERE, f"y_{name}.txt")
        np.savetxt(out, y, fmt="%.12g",
                   header=f"reference replay output: mode={mode or 'none'}, "
                          f"step={step}, L={L}, M={M}, T={T}, fd={fd_scale} Hz\n"
                          f"generated by gen_references.py from {REF_REPO}@{REF_COMMIT[:12]}\n"
                          f"columns are receivers, rows are samples at fs={FS_IN:.0f} Sa/s")
        print(f"{name:6s} step={step:2d} fd={fd_scale:5.1f} Hz -> {y.shape} "
              f"peak={np.abs(y).max():.4f} -> {os.path.basename(out)}")


if __name__ == "__main__":
    main()
