project:
  type: website

website:
  title: "UnderwaterAcoustics.jl"
  navbar:
    search: true
  sidebar:
    style: "docked"
    contents:
    - section: <b>UnderwaterAcoustics.jl</b>
      contents:
      - index.qmd
      - text: <b>Quickstart</b>
      - quickstart.qmd
      - replay.qmd
      - text: <b>Guides</b>
      - pos.qmd
      - fields.qmd
      - ext.qmd
      - porting.qmd
      - python.qmd
      - text: <b>Tutorials</b>
      - tut1.qmd
      - tut2.qmd
      - tut3.qmd
      - tut4.qmd
      - text: <b>API reference</b>
      - basic.qmd
      - api.qmd
    - text: "---"
    - section: <b>Propagation models</b>
      contents:
      - text: <b>UnderwaterAcoustics.jl</b>
      - pekeris-rays.qmd
      - pekeris-modes.qmd
      - text: <b>AcousticsToolbox.jl</b>
      - bellhop.qmd
      - kraken.qmd
      - orca.qmd
      - text: <b>AcousticRayTracers.jl</b>
      - raysolver.qmd
    - text: "---"
    - section: <b>Notes</b>
      contents:
      - modes.qmd
    - text: "---"
    - section: <b>Related tools</b>
      contents:
      - text: VirtualAcousticOcean.jl
        href: https://github.com/org-arl/VirtualAcousticOcean.jl

execute:
  echo: true
  freeze: auto

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

bibliography: references.bib
